include theos/makefiles/common.mk

BUNDLE_NAME = FakeOperatorPreferences
FakeOperatorPreferences_FILES = FakeOperatorPreferences.mm
FakeOperatorPreferences_INSTALL_PATH = /Library/PreferenceBundles
FakeOperatorPreferences_FRAMEWORKS = UIKit
FakeOperatorPreferences_PRIVATE_FRAMEWORKS = Preferences

include theos/makefiles/bundle.mk